name = "law-yale"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "law-yale-db"
database_id = "b3a8ce2f-26bc-4ff8-8837-34d5cf341c65"

[env.production]
name = "law-yale"

[env.production.d1_databases]
binding = "DB"
database_name = "law-yale-db"
database_id = "b3a8ce2f-26bc-4ff8-8837-34d5cf341c65"
